version: 1.0.{build}
image: Visual Studio 2017

environment:
  CONFIG_PATH: data/local_config.yml

  matrix:
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - python -m pip install -U pip
  - python -m pip install -U pytest
  - python -m pip install -r requirements.txt
  - python -m pip install -r api/requirements.txt
  - python -m pip install -r testing/requirements.txt
  - ps: docker-compose --version
  - ps: docker --version

before_build:
  - ps: $ifIndex = Get-NetIPInterface | Where-Object -FilterScript { $_.InterfaceAlias -Eq "Ethernet 7" -And $_.AddressFamily -Eq "IPv4"} | Select-Object -ExpandProperty ifIndex
  - ps: $ipAddr = Get-NetIPAddress -InterfaceIndex $ifIndex | Where-Object -FilterScript {$_.AddressFamily -Eq "IPv4"} | Select-Object -ExpandProperty IPAddress
  - ps: docker swarm init --advertise-addr $ipAddr

build_script:
  - ps: docker build -t walkoff_bootloader -f bootloader/Dockerfile .
  - ps: .\test.ps1
  - ps: docker images

test_script:
  - ps: python -m pytest testing\api\
